{
 "title": "Interface Status SQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Down Interface Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "interface_status",
     "rawSql": "SELECT count(*) FROM interface_status.status where status = 'down/down';"
    }
   ]
  },
  {
   "title": "Up Interface Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "interface_status",
     "rawSql": "SELECT count(*) FROM interface_status.status where status = 'up/up';"
    }
   ]
  },
  {
   "title": "Up Interface Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "interface_status",
     "rawSql": "SELECT count(*) FROM interface_status.status where status = 'administratively down/down';"
    }
   ]
  },
  {
   "title": "Interface Count",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "interface_status",
     "rawSql": "select site, sum(case when status = 'up/up' then 1 else 0 end) as up, sum(case when status = 'down/down' then 1 else 0 end) as down, sum(case when status = 'administratively down/down' then 1 else 0 end) as 'admin down' from interface_status.status group by site;\n"
    }
   ]
  }
 ]
}